Xevlabs/mlc-models-library

enums/client-account-status.enum.ts
index.ts
nationality/nationality.model.ts
user/client-info.model.ts

for [MLVC-112]
[MLVC-112]: https://xevlabs.atlassian.net/browse/MLVC-112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

completed the clientInfoModel. Added the nationality model.

---

user/client.model.ts

for [MLVC-112]
[MLVC-112]: https://xevlabs.atlassian.net/browse/MLVC-112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

added ClientRegistrationResponseBodyModel

---

address/address.model.ts
user/user-kyc.model.ts

made state attribute in address optional

---

user/client.model.ts

Fixed client model to match what we received

Fixed client model

---

treezor-api/treezor-api.model.ts
user/client.model.ts

for [MLVC-135]
[MLVC-135]: https://xevlabs.atlassian.net/browse/MLVC-135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

updated models for client update

---

enums/treezor-api-wallet-status.enum.ts
index.ts
treezor-api/treezor-api.model.ts

for [MLVC-146]
[MLVC-146]: https://xevlabs.atlassian.net/browse/MLVC-146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

extended the TreezorApiWalletModel

---

user/client.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/54

added extendedClientEditionFormModel to update username on email change

---

locale/locale.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/56

added locale model

---

base/base.model.ts
index.ts
note/note.model.ts
user/kyc/kyc-log.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/58

added NoteModel, updated KycLogModel and added StrapiBaseModel

---

user/client-info.model.ts
user/client.model.ts
user/user.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/60

updated models for by_user fields

---

base/base.model.ts
note/note.model.ts

NOT JIRA RELATED
Given how the postman response for the client notes returns the whole user that created the note, I added a new base model and made the NoteModel extend it so it's more accurate

note model adjustments

---

base/base.model.ts

extended timestamp model in populated base model

---

user/fireblocks-user.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/68

removed unused fields from the FireblocksUserFormModel

---

adjusted-treezor-wallet/adjusted-treezor-wallet.model.ts
index.ts
transaction/transaction.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/88

added AdjustedTreezorWalletModel

---

adjusted-fireblocks-vault/adjusted-fireblocks-vault.model.ts
common-fireblocks-vault/extended-fireblocks-vault-account.ts
common-fireblocks-vault/extended-fireblocks-vault-asset.ts
fireblocks-transaction/fireblocks-transaction.model.ts
index.ts
transaction/transaction.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/90

added models for adjusted fireblocks vaults

---

adjusted-fireblocks-vault/adjusted-fireblocks-vault.model.ts
common-fireblocks-vault/extended-fireblocks-vault-asset.ts

for https://github.com/Xevlabs/mlc-backend/pull/96

changed adjusted fireblocks wallets to have values before and after transactions

---

world-check-api/world-check-api.model.ts
world-check-settings/world-check-settings.model.ts

NOT JIRA RELATED fixed problematic imports

removed typings import

---

transaction/transaction.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/117

added the user in the transaction details

---

fireblocks-transaction/fireblocks-transaction.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/119

added fireblocksTransactionId

---

enums/inputType.enum.ts
enums/transaction-status.enum.ts

for https://github.com/Xevlabs/mlc-backend/pull/123

added failed tatus for transations

---

treezor-transfer/treezor-transfer.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/125

added treezorErrorResponse field to treezorTransfers

---

treezor-transfer/treezor-transfer.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/121

added the user to TreezorTransfers

---

treezor-kyc-document/treezor-kyc-document.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/132

NOT JIRA RELATED fixed treezorKycDocumentModel which can have null dates

---

settings/settings.model.ts

added depositMin and withdrawalMin

Feature/Minimum Transaction Amount

---

user/kyc/kyc-document.model.ts

changed type field to type string in kyc document model

feature/ upload kyc document

---

transaction/transaction.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/153

fixed camelCase in TransactionDetailsModel

---

user/kyc/kyc-document.model.ts

changed file attribute to document

feature/ display mlc kyc doc

---

enums/payout-refund-status.enum.ts
enums/treezor-api-payout-refund-status.enum.ts
index.ts
pay-out/pay-out.model.ts
treezor-api/treezor-api-payout-refund.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/173

created and adapted models related to payout refunds

---

adjusted-treezor-wallet/adjusted-treezor-wallet.model.ts
investment/investment.model.ts
treezor-api/treezor-api.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/174

added the client's model for investment

---

transaction/transaction.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/177

added the clientTransactionModel

---

beneficiary/beneficiary.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/187

edited ClientBeneficiaryModel to match what's expected from the GET users/me/beneficiaries endpoint

---

beneficiary/beneficiary.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/187

fixed placement of extend TimeStampModel for Benefiociary models

---

user/client.model.ts

added treezorUser to ClientRegistrationFormModel

fix/ client edit tax residence 

---

index.ts
investment-report/investment-report.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/226

added investmentReport

---

index.ts

for https://github.com/Xevlabs/mlc-web/pull/173

added a missing export

---

user/client.model.ts

for https://github.com/Xevlabs/mlc-web/pull/185

added clientLimitedEditionModel

---

investment/investment.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/240

added the otalInvestmentModel

---

index.ts
total-investment-log/total-investment-log.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/244

added models for total investment logs

---

enums/gender.enum.ts
hubspot-settings/hubspot-settings.model.ts
hubspot-user/hubspot-user.model.ts
index.ts

for https://github.com/Xevlabs/mlc-backend/pull/249

added models for hubspot

---

hubspot-user/hubspot-user.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/252

added attributes to the HubspotUserModel

---

hubspot-settings/hubspot-settings.model.ts
hubspot-user/hubspot-user.model.ts
user/client-info.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/253

some little fixes for models linked to the hubspot user

---

hubspot-settings/hubspot-settings.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/256

added the registrationWaitingTreezorReviewStageLabel and registrationWaitingBaseScoreStageLabel in HubspotSettings

---

hubspot-user/hubspot-user.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/267

added attributes linked to the last transaction to the HubspotUser

---

hubspot-settings/hubspot-settings.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/268

added ids to Hubspot settings. Added models for the hubspot service

---

hubspot-user/hubspot-user.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/270

added adjusted and authorized treezor wallet to the hubspot user

---

hubspot-user/hubspot-user.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/271

added nationality and patrimony to hubspot user

---

pay-in/pay-in.model.ts
pay-out/pay-out.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/283

added validatedAt to payins and payouts

---

pay-out/pay-out.model.ts

for https://github.com/Xevlabs/mlc-backend/pull/285

added label to PayoutFormModel

---

enums/range.enum.ts
index.ts
investment-report/investment-report.model.ts

for https://github.com/Xevlabs/mlc-web/pull/297

added model and enum for the investment chart
